services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: yii2-app
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    container_name: yii2-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: yii2-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: track
    ports:
      - "5432:5432"
    volumes:
      - .docker/db:/var/lib/postgresql/data

  db_test:
    image: postgres:15
    container_name: yii2-test-db
    environment:
      POSTGRES_DB: track_test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - .docker/db_test:/var/lib/postgresql/data